# app/services/github_pr_service.py
"""
GitHub PR service for promoting AI-generated tools to code review.

Uses PyGitHub to:
  1. Create a feature branch from the target branch HEAD.
  2. Commit the promoted static tool code to app/agents/tools/tools_lib/gen_<name>_tools.py
  3. Open a PR with structured metadata from the tool registry.
  4. Return pr_url and pr_number for registry storage.

No git binary is required on the server — PyGitHub talks directly to the GitHub
REST API over HTTPS using a PAT.
"""

from dataclasses import dataclass
from typing import Optional

from github import Github, GithubException

from app.core.config import settings
from app.utils.logger_config import setup_logging

logger = setup_logging(app_name="kubeintellect")


@dataclass
class PRCreationResult:
    success: bool
    pr_url: Optional[str] = None
    pr_number: Optional[int] = None
    branch_name: Optional[str] = None
    error: Optional[str] = None


class GitHubPRService:
    """
    Stateless GitHub PR creator for AI-generated tools.

    Instantiated fresh per call — no shared state between requests.
    All configuration is read from `settings` at call time.
    """

    def _is_configured(self) -> bool:
        return bool(
            settings.GITHUB_PR_ENABLED
            and settings.GITHUB_TOKEN
            and settings.GITHUB_REPO
        )

    def _build_branch_name(self, tool_name: str, tool_id: str) -> str:
        """Branch pattern: tool/<tool_name_slug>/<tool_id_8chars>"""
        slug = tool_name.replace("_", "-").lower()
        return f"tool/{slug}/{tool_id[:8]}"

    def _build_file_path(self, tool_name: str) -> str:
        """
        Target path in the repo. The gen_ prefix marks unreviewed AI-generated tools.
        Reviewers rename the file (drop the prefix) as part of the review process.
        """
        return f"app/agents/tools/tools_lib/gen_{tool_name}_tools.py"

    def _build_pr_title(self, tool_name: str) -> str:
        return f"feat(tools): add AI-generated tool `{tool_name}`"

    def _build_pr_body(self, tool_meta: dict) -> str:
        tool_id = tool_meta["tool_id"]
        tool_name = tool_meta["name"]
        description = tool_meta.get("description", "")
        created_at = tool_meta.get("created_at", "unknown")
        function_name = tool_meta.get("function_name", "unknown")
        checksum = tool_meta.get("file_checksum", "n/a")

        input_schema = tool_meta.get("input_schema", {})
        if input_schema:
            schema_rows = "\n".join(
                f"| `{p}` | `{info.get('type', 'str')}` | {info.get('description', '')} |"
                for p, info in input_schema.items()
            )
            schema_table = (
                "| Parameter | Type | Description |\n"
                "|-----------|------|-------------|\n"
                + schema_rows
            )
        else:
            schema_table = "_No parameters._"

        return f"""\
## AI-Generated Tool: `{tool_name}`

This PR was automatically created by KubeIntellect's CodeGenerator agent after the tool
was registered, tested in the live cluster, and loaded into the LangGraph agent.

### Metadata

| Field | Value |
|-------|-------|
| Tool ID | `{tool_id}` |
| Function name | `{function_name}` |
| Created at | `{created_at}` |
| File checksum (PVC) | `{checksum}` |

### Description

{description}

### Input Schema

{schema_table}

### Review Checklist

- [ ] Function handles API errors gracefully and returns a dict with `status` key
- [ ] No hardcoded resource names, namespaces, or cluster-specific values
- [ ] Imports are inside the function body (per project convention for generated tools)
- [ ] Rename file from `gen_{tool_name}_tools.py` → `{tool_name}_tools.py` after approval
- [ ] Add import in `app/agents/tools/kubernetes_tools.py`
- [ ] Add to the relevant agent's tool list in `app/orchestration/workflow.py`
- [ ] Disable or delete runtime tool after merge: `PATCH /v1/tools/{tool_id}/status` → `disabled`

---
_Generated by KubeIntellect CodeGenerator — review carefully before merging._
"""

    def create_pr_for_tool(
        self,
        tool_meta: dict,
        promoted_code: str,
    ) -> PRCreationResult:
        """
        Create a GitHub PR for a runtime-generated tool.

        Args:
            tool_meta: Full registry entry dict for the tool.
            promoted_code: The static tool code (output of promote_tool logic).

        Returns:
            PRCreationResult — check .success before using other fields.
        """
        if not self._is_configured():
            return PRCreationResult(
                success=False,
                error=(
                    "GitHub PR creation is not configured. "
                    "Set GITHUB_PR_ENABLED=true, GITHUB_TOKEN, and GITHUB_REPO."
                ),
            )

        tool_id = tool_meta["tool_id"]
        tool_name = tool_meta["name"]

        try:
            gh = Github(settings.GITHUB_TOKEN)
            repo = gh.get_repo(settings.GITHUB_REPO)
        except GithubException as e:
            return PRCreationResult(
                success=False,
                error=f"Failed to connect to GitHub repo '{settings.GITHUB_REPO}': {e}",
            )

        branch_name = self._build_branch_name(tool_name, tool_id)
        file_path = self._build_file_path(tool_name)

        try:
            # 1. Get HEAD SHA of the target branch
            target_ref = repo.get_branch(settings.GITHUB_PR_TARGET_BRANCH)
            head_sha = target_ref.commit.sha

            # 2. Create the feature branch (idempotent — 422 means it already exists)
            try:
                repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=head_sha)
                logger.info(f"Created branch '{branch_name}' from '{settings.GITHUB_PR_TARGET_BRANCH}' @ {head_sha[:8]}")
            except GithubException as e:
                if e.status == 422:
                    logger.warning(f"Branch '{branch_name}' already exists — will update the file.")
                else:
                    raise

            # 3. Create or update the tool file on the feature branch
            commit_message = f"feat(tools): add AI-generated tool {tool_name} (ID: {tool_id})"
            try:
                existing = repo.get_contents(file_path, ref=branch_name)
                repo.update_file(
                    path=file_path,
                    message=commit_message,
                    content=promoted_code,
                    sha=existing.sha,
                    branch=branch_name,
                )
                logger.info(f"Updated '{file_path}' on branch '{branch_name}'")
            except GithubException as e:
                if e.status == 404:
                    repo.create_file(
                        path=file_path,
                        message=commit_message,
                        content=promoted_code,
                        branch=branch_name,
                    )
                    logger.info(f"Created '{file_path}' on branch '{branch_name}'")
                else:
                    raise

            # 4. Open the PR
            pr = repo.create_pull(
                title=self._build_pr_title(tool_name),
                body=self._build_pr_body(tool_meta),
                head=branch_name,
                base=settings.GITHUB_PR_TARGET_BRANCH,
            )

            # 5. Apply labels (best-effort — labels must pre-exist in the repo)
            labels = [lbl.strip() for lbl in settings.GITHUB_PR_LABELS.split(",") if lbl.strip()]
            if labels:
                try:
                    pr.set_labels(*labels)
                except GithubException as label_err:
                    logger.warning(f"Could not apply labels to PR #{pr.number}: {label_err}")

            logger.info(f"Created PR #{pr.number} for tool '{tool_name}': {pr.html_url}")
            return PRCreationResult(
                success=True,
                pr_url=pr.html_url,
                pr_number=pr.number,
                branch_name=branch_name,
            )

        except GithubException as e:
            msg = f"GitHub API error during PR creation for tool '{tool_name}': {e}"
            logger.error(msg, exc_info=True)
            return PRCreationResult(success=False, error=msg)
        except Exception as e:
            msg = f"Unexpected error during PR creation for tool '{tool_name}': {e}"
            logger.error(msg, exc_info=True)
            return PRCreationResult(success=False, error=msg)


def create_github_pr_for_tool(tool_meta: dict, promoted_code: str) -> PRCreationResult:
    """Module-level convenience wrapper — instantiates the service and delegates."""
    return GitHubPRService().create_pr_for_tool(tool_meta, promoted_code)
