kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6443
        listenAddress: "0.0.0.0"
      - containerPort: 80    # ingress HTTP
        hostPort: 80
      - containerPort: 443   # ingress HTTPS
        hostPort: 443
    extraMounts:
      - hostPath: ${PROJECT_ROOT}/.local-data/postgres
        containerPath: /mnt/data/postgres
      - hostPath: ${PROJECT_ROOT}/app
        containerPath: /mnt/code/app
  - role: worker
