---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	entry_processor(entry_processor)
	intent_detector(intent_detector)
	actual_list_pods_agent(actual_list_pods_agent)
	get_deployment_agent(get_deployment_agent)
	describe_deployment_agent(describe_deployment_agent)
	scale_deployment_agent(scale_deployment_agent)
	view_logs_agent(view_logs_agent)
	final_response_formulator(final_response_formulator)
	__end__([<p>__end__</p>]):::last
	__start__ --> entry_processor;
	actual_list_pods_agent --> final_response_formulator;
	describe_deployment_agent --> final_response_formulator;
	entry_processor --> intent_detector;
	final_response_formulator --> __end__;
	get_deployment_agent --> final_response_formulator;
	scale_deployment_agent --> final_response_formulator;
	view_logs_agent --> final_response_formulator;
	intent_detector -.-> actual_list_pods_agent;
	intent_detector -.-> get_deployment_agent;
	intent_detector -.-> describe_deployment_agent;
	intent_detector -.-> scale_deployment_agent;
	intent_detector -.-> view_logs_agent;
	intent_detector -.-> final_response_formulator;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
