"""L0 file plane (v5 P2): CLUSTER.md + MEMORY.md projections of the memory.

Files are a *projection*, Postgres is the source of truth (C9): the consolidation worker
regenerates two bounded (≤25 KB) markdown files per cluster — CLUSTER.md (recent known state) and
MEMORY.md (the learned-memory digest: themes + recurring resolutions). They give a human or a
file-native agent a cheap, greppable read of what the system knows, without a DB round-trip.

The render functions are pure (take already-fetched data); ``regenerate_file_plane`` is an
injectable orchestrator (fetchers + writer) so the whole thing is unit-testable with no DB/FS.
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from pathlib import Path
from typing import Any, Optional

from app.utils.logger import get_logger

logger = get_logger(__name__)

DEFAULT_MAX_BYTES = 25_000
_PROJECTION_NOTE = ("_Projection — Postgres is the source of truth; this file is regenerated by the "
                    "consolidation worker._")


def _bound_bytes(text: str, max_bytes: int) -> str:
    """Cap ``text`` to ``max_bytes`` UTF-8 bytes on a line boundary, never mid-line, never silent."""
    encoded = text.encode("utf-8")
    if len(encoded) <= max_bytes:
        return text
    marker = "\n…[truncated to fit the ≤25KB file-plane budget]"
    budget = max_bytes - len(marker.encode("utf-8"))
    cut = encoded[:max(0, budget)].decode("utf-8", "ignore")
    nl = cut.rfind("\n")
    if nl > 0:
        cut = cut[:nl]
    return cut.rstrip() + marker


def render_cluster_md(cluster_id: str, episodes: list[dict[str, Any]], *,
                      max_bytes: int = DEFAULT_MAX_BYTES) -> str:
    """Project recent known cluster state (namespaces seen, recent episodes) to markdown."""
    lines = [f"# CLUSTER.md — {cluster_id}", "", _PROJECTION_NOTE, ""]
    namespaces = sorted({str(ep.get("namespace")) for ep in episodes if ep.get("namespace")})
    if namespaces:
        lines.append("## Namespaces seen")
        lines.extend(f"- {ns}" for ns in namespaces)
        lines.append("")
    lines.append("## Recent episodes")
    if not episodes:
        lines.append("_none recorded yet_")
    for ep in episodes:
        outcome = ep.get("outcome") or "report_only"
        summary = (ep.get("summary") or "").replace("\n", " ")[:200]
        lines.append(f"- [{outcome}] {summary}")
    return _bound_bytes("\n".join(lines), max_bytes)


def render_memory_md(cluster_id: str, themes_block: str, episodes: list[dict[str, Any]], *,
                     max_bytes: int = DEFAULT_MAX_BYTES) -> str:
    """Project the learned-memory digest (themes + recurring verified resolutions) to markdown."""
    lines = [f"# MEMORY.md — {cluster_id}", "", _PROJECTION_NOTE, ""]
    if themes_block.strip():
        lines.append(themes_block.strip())
        lines.append("")
    lines.append("## Recurring resolutions")
    resolutions = [ep for ep in episodes if ep.get("verified") and ep.get("root_cause")]
    if not resolutions:
        lines.append("_no verified resolutions yet_")
    for ep in resolutions:
        rc = str(ep.get("root_cause"))[:160]
        summary = (ep.get("summary") or "").replace("\n", " ")[:160]
        lines.append(f"- **{rc}** — {summary}")
    return _bound_bytes("\n".join(lines), max_bytes)


EpisodeFetcher = Callable[[str], Awaitable[list[dict[str, Any]]]]
ThemesFetcher = Callable[[str], Awaitable[str]]
Writer = Callable[[Path, str], None]


def _default_writer(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


async def _default_episodes(cluster_id: str) -> list[dict[str, Any]]:
    from app.memory.episodes import recall_episodes
    # Broad recall to surface a representative recent/important slice (projection, not a search).
    return await recall_episodes("incident failure error outage", cluster_id, k=15)


async def _default_themes(cluster_id: str) -> str:
    from app.memory.summaries import recall_theme_summaries, render_summaries_block
    return render_summaries_block(await recall_theme_summaries("incident", cluster_id, k=5))


async def regenerate_file_plane(
    cluster_id: str,
    out_dir: str | Path,
    *,
    fetch_episodes: Optional[EpisodeFetcher] = None,
    fetch_themes: Optional[ThemesFetcher] = None,
    writer: Optional[Writer] = None,
    max_bytes: int = DEFAULT_MAX_BYTES,
) -> dict[str, int]:
    """Regenerate CLUSTER.md + MEMORY.md for ``cluster_id`` into ``out_dir``. Returns byte counts.

    Never raises out — a projection failure must not break the consolidation pass.
    """
    fetch_episodes = fetch_episodes or _default_episodes
    fetch_themes = fetch_themes or _default_themes
    writer = writer or _default_writer
    out = Path(out_dir)
    try:
        episodes = await fetch_episodes(cluster_id)
        themes_block = await fetch_themes(cluster_id)
        cluster_md = render_cluster_md(cluster_id, episodes, max_bytes=max_bytes)
        memory_md = render_memory_md(cluster_id, themes_block, episodes, max_bytes=max_bytes)
        writer(out / "CLUSTER.md", cluster_md)
        writer(out / "MEMORY.md", memory_md)
        return {
            "cluster_md_bytes": len(cluster_md.encode("utf-8")),
            "memory_md_bytes": len(memory_md.encode("utf-8")),
        }
    except Exception as exc:
        logger.warning("file_plane regenerate failed: %s", exc)
        return {"cluster_md_bytes": 0, "memory_md_bytes": 0}
