#!/usr/bin/env bash
# generate-kind-secrets.sh
#
# Reads .env and emits charts/kubeintellect/values-kind-secrets.yaml — a gitignored
# Helm overlay that supplies real credentials to Kind/local deployments.
#
# Usage:
#   bash scripts/dev/generate-kind-secrets.sh          # skip if file already exists
#   bash scripts/dev/generate-kind-secrets.sh --force  # always regenerate
#   make kind-generate-secrets                         # same as above (no --force)
#   make kind-generate-secrets FORCE=--force           # force regenerate
#
# The output file is gitignored and layered over values-kind.yaml:
#   helm ... -f values-kind.yaml -f values-kind-secrets.yaml
#
# IMPORTANT: values-kind.yaml holds public defaults (non-secret config).
#            values-kind-secrets.yaml holds credentials — never commit it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
OUTPUT="$REPO_ROOT/charts/kubeintellect/values-kind-secrets.yaml"
FORCE="${1:-}"

# ─── Skip if already generated ─────────────────────────────────────────────
if [[ -f "$OUTPUT" && "$FORCE" != "--force" ]]; then
  echo "  ✔  $OUTPUT already exists. Skipping."
  echo "     Run with --force to regenerate (rotates LibreChat session secrets)."
  exit 0
fi

# ─── Load .env ──────────────────────────────────────────────────────────────
if [[ ! -f "$ENV_FILE" ]]; then
  echo ""
  echo "  ERROR: .env not found."
  echo ""
  echo "  Run:  cp .env.example .env"
  echo "  Then fill in AZURE_OPENAI_API_KEY and other required values."
  echo ""
  exit 1
fi

# Source .env — skip blank lines and comments
set -a
# shellcheck disable=SC1090
source <(grep -v '^[[:space:]]*#' "$ENV_FILE" | grep -v '^[[:space:]]*$' | grep '=')
set +a

# ─── Validate required vars ─────────────────────────────────────────────────
MISSING=()
[[ -z "${AZURE_OPENAI_API_KEY:-}" ]] && MISSING+=(AZURE_OPENAI_API_KEY)

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo ""
  echo "  ERROR: The following required variables are not set in .env:"
  for v in "${MISSING[@]}"; do echo "    - $v"; done
  echo ""
  echo "  Edit .env and re-run."
  exit 1
fi

# ─── Optional vars with defaults ────────────────────────────────────────────
LANGCHAIN_API_KEY="${LANGCHAIN_API_KEY:-}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-password}"
DEV_USER_EMAIL="${DEV_USER_EMAIL:-admin@kubeintellect.local}"
DEV_USER_PASSWORD="${DEV_USER_PASSWORD:-changeme}"

# ─── Langfuse API keys ──────────────────────────────────────────────────────
# These must match between kubeintellect-core-secret and langfuse.initProject.
# If set in .env they are reused across regenerations; otherwise generated once.
GENERATED_KEYS=""

if [[ -z "${LANGFUSE_PUBLIC_KEY:-}" ]]; then
  LANGFUSE_PUBLIC_KEY="pk-lf-$(openssl rand -hex 12)"
  GENERATED_KEYS+="  LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}\n"
fi
if [[ -z "${LANGFUSE_SECRET_KEY:-}" ]]; then
  LANGFUSE_SECRET_KEY="sk-lf-$(openssl rand -hex 12)"
  GENERATED_KEYS+="  LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}\n"
fi

# ─── LibreChat session secrets (always regenerated) ─────────────────────────
# These are used for JWT signing and credential encryption inside LibreChat.
# Rotating them invalidates all active LibreChat sessions.
MEILI_MASTER_KEY="$(openssl rand -hex 20)"
JWT_SECRET="$(openssl rand -hex 32)"
JWT_REFRESH_SECRET="$(openssl rand -hex 32)"
CREDS_KEY="$(openssl rand -hex 32)"
CREDS_IV="$(openssl rand -hex 16)"

# ─── Langfuse encryption key ────────────────────────────────────────────────
LANGFUSE_ENCRYPTION_KEY="$(openssl rand -hex 32)"

# ─── Postgres password base64 ───────────────────────────────────────────────
POSTGRES_PASSWORD_B64="$(echo -n "${POSTGRES_PASSWORD}" | base64)"

# ─── Write output ───────────────────────────────────────────────────────────
cat > "$OUTPUT" <<YAML
# =============================================================================
# GENERATED FILE — DO NOT COMMIT (gitignored)
# =============================================================================
# Generated by: scripts/dev/generate-kind-secrets.sh
# Re-generate:  make kind-generate-secrets
# Force rotate: bash scripts/dev/generate-kind-secrets.sh --force
#
# This file is layered over charts/kubeintellect/values-kind.yaml:
#   helm ... -f values-kind.yaml -f values-kind-secrets.yaml
#
# The 'secrets:' key replaces the entire secrets array from values-kind.yaml.
# Scalar overrides (langfuse.*) are deep-merged by Helm.
# =============================================================================

# ─── KubeIntellect & LibreChat secrets ───────────────────────────────────────
secrets:
  # 1. KubeIntellect core app secret
  - name: kubeintellect-core-secret
    enabled: true
    type: Opaque
    stringData:
      AZURE_OPENAI_API_KEY: "${AZURE_OPENAI_API_KEY}"
      LANGCHAIN_API_KEY: "${LANGCHAIN_API_KEY}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      # Langfuse keys — must match langfuse.initProject.* below
      LANGFUSE_PUBLIC_KEY: "${LANGFUSE_PUBLIC_KEY}"
      LANGFUSE_SECRET_KEY: "${LANGFUSE_SECRET_KEY}"

  # 2. Docker registry credentials (GHCR images are public — disabled by default)
  - name: ghcr-creds
    enabled: false
    type: kubernetes.io/dockerconfigjson
    data:
      .dockerconfigjson: ""

  # 3. PostgreSQL DB secret
  - name: postgres-secret
    enabled: true
    type: Opaque
    data:
      password: ${POSTGRES_PASSWORD_B64}

  # 4. LibreChat session secrets (JWT signing, search, credential encryption)
  - name: librechat-secret
    enabled: true
    type: Opaque
    stringData:
      MONGO_URI: "mongodb://mongodb:27017/LibreChat"
      MEILI_MASTER_KEY: "${MEILI_MASTER_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      CREDS_KEY: "${CREDS_KEY}"
      CREDS_IV: "${CREDS_IV}"

# ─── Langfuse scalar overrides ───────────────────────────────────────────────
# Helm deep-merges these scalars — no array replacement needed.
langfuse:
  encryptionKey: "${LANGFUSE_ENCRYPTION_KEY}"
  initProject:
    # Must match LANGFUSE_PUBLIC_KEY / LANGFUSE_SECRET_KEY in kubeintellect-core-secret above
    publicKey: "${LANGFUSE_PUBLIC_KEY}"
    secretKey: "${LANGFUSE_SECRET_KEY}"

# ─── Dev user (for make kind-dev-create-user) ────────────────────────────────
# Not a Helm value — read by the Makefile to pass EMAIL/PASSWORD to create-dev-user.sh.
# Stored here so all credentials are in one generated file.
# devUser:
#   email: "${DEV_USER_EMAIL}"
#   password: "${DEV_USER_PASSWORD}"
YAML

echo ""
echo "  ✔  Generated: $OUTPUT"

if [[ -n "$GENERATED_KEYS" ]]; then
  echo ""
  echo "  The following Langfuse keys were auto-generated."
  echo "  Add them to .env to reuse across regenerations (avoids key rotation on --force):"
  echo ""
  echo -e "$GENERATED_KEYS"
fi

echo ""
echo "  Dev user:"
echo "    Email:    ${DEV_USER_EMAIL}"
echo "    Password: ${DEV_USER_PASSWORD}"
echo ""
echo "  Next: make kind-kubeintellect-deploy"
echo ""
