"""`kq completion [bash|zsh|fish]` — print a shell completion script.

The script completes `kq` subcommands, their second-level verbs (`config show`,
`detector new`, ...), notable per-command flags, and the global flags. Everything
is generated from the central registry (`subcommands.py`), so completion never
drifts from the actual command set.

Install:
    # bash — add to ~/.bashrc
    source <(kq completion bash)
    # zsh  — add to ~/.zshrc (before compinit, or into a dir on $fpath)
    source <(kq completion zsh)
    # fish
    kq completion fish | source     # or write to ~/.config/fish/completions/kq.fish
"""

from __future__ import annotations

from kube_q.cli import subcommands

SHELLS = ("bash", "zsh", "fish")

# Curated global flags offered by completion. A drift test asserts each one still
# appears in `kq --help`, so a renamed/removed flag is caught. (Long forms only —
# short aliases like -q/-h are handled by the shell's default flag matching.)
GLOBAL_FLAGS = [
    "--url",
    "--query",
    "--no-stream",
    "--conversation-id",
    "--session-id",
    "--list",
    "--search",
    "--user-id",
    "--no-banner",
    "--api-key",
    "--ca-cert",
    "--output",
    "--user-name",
    "--agent-name",
    "--model",
    "--no-health-check",
    "--debug",
    "--backend",
    "--openai-api-key",
    "--openai-endpoint",
    "--azure-openai-api-key",
    "--azure-openai-endpoint",
    "--azure-openai-deployment",
    "--profile",
    "--context",
    "--auto-approve",
    "--version",
    "--help",
]


def _command_tokens() -> list[str]:
    """All first-position tokens: registry commands + help aliases."""
    return list(subcommands.names()) + list(subcommands.help_alias_names())


def _words_for(name: str) -> list[str]:
    """Second-level verbs + flags (+ --help) offered after `kq <name>`."""
    hints = subcommands.completion_hints(name)
    return [*hints["verbs"], *hints["flags"], "--help"]


def _sanitize(text: str) -> str:
    """Drop single quotes so descriptions are safe inside single-quoted shell strings."""
    return text.replace("'", "")


# ── bash ─────────────────────────────────────────────────────────────────────


def _bash_script() -> str:
    commands = " ".join(_command_tokens())
    global_flags = " ".join(GLOBAL_FLAGS)
    arms = "\n".join(
        f'        {name}) __kq_words="{" ".join(_words_for(name))}" ;;'
        for name in subcommands.names()
    )
    return f"""# bash completion for kq — generated by `kq completion bash`
_kq_complete() {{
    local cur commands global_flags __kq_words
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    commands="{commands}"
    global_flags="{global_flags}"

    if [ "$COMP_CWORD" -eq 1 ]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "$commands $global_flags" -- "$cur") )
        fi
        return 0
    fi

    __kq_words="--help"
    case "${{COMP_WORDS[1]}}" in
{arms}
    esac
    COMPREPLY=( $(compgen -W "$__kq_words $global_flags" -- "$cur") )
    return 0
}}
complete -F _kq_complete kq
"""


# ── zsh ──────────────────────────────────────────────────────────────────────


def _zsh_script() -> str:
    descs = "\n".join(
        f"    '{name}:{_sanitize(desc)}'" for name, desc in subcommands.describe()
    )
    global_flags = " ".join(GLOBAL_FLAGS)
    arms = "\n".join(
        f"        {name}) opts=({' '.join(_words_for(name))}) ;;"
        for name in subcommands.names()
    )
    return f"""#compdef kq
# zsh completion for kq — generated by `kq completion zsh`
_kq() {{
  local -a commands
  commands=(
{descs}
  )
  if (( CURRENT == 2 )); then
    _describe 'kq command' commands
    compadd -- {global_flags}
    return
  fi
  local -a opts
  case ${{words[2]}} in
{arms}
        *) opts=(--help) ;;
  esac
  compadd -- $opts {global_flags}
}}
compdef _kq kq
"""


# ── fish ─────────────────────────────────────────────────────────────────────


def _fish_script() -> str:
    lines = [
        "# fish completion for kq — generated by `kq completion fish`",
        "complete -c kq -f",
        "",
        "# subcommands (offered only when no subcommand has been given yet)",
    ]
    for name, desc in subcommands.describe():
        lines.append(
            f"complete -c kq -n '__fish_use_subcommand' -a '{name}' -d '{_sanitize(desc)}'"
        )
    lines.append("")
    lines.append("# second-level verbs and per-command flags")
    for name in subcommands.names():
        hints = subcommands.completion_hints(name)
        if hints["verbs"]:
            verbs = " ".join(hints["verbs"])
            lines.append(
                f"complete -c kq -n '__fish_seen_subcommand_from {name}' -a '{verbs}'"
            )
        for flag in hints["flags"]:
            lines.append(
                f"complete -c kq -n '__fish_seen_subcommand_from {name}' "
                f"-l {flag.lstrip('-')}"
            )
    lines.append("")
    lines.append("# global flags")
    for flag in GLOBAL_FLAGS:
        lines.append(f"complete -c kq -l {flag.lstrip('-')}")
    return "\n".join(lines) + "\n"


_GENERATORS = {"bash": _bash_script, "zsh": _zsh_script, "fish": _fish_script}


def script_for(shell: str) -> str:
    """Return the completion script for *shell* (bash/zsh/fish)."""
    return _GENERATORS[shell]()


def _usage() -> None:
    from kube_q.cli.renderer import console

    console.print("Usage: [cyan]kq completion [bash|zsh|fish][/cyan]\n")
    console.print("Print a shell completion script. Enable it with:\n")
    console.print("  [dim]# bash[/dim]  source <(kq completion bash)      # add to ~/.bashrc")
    console.print("  [dim]# zsh [/dim]  source <(kq completion zsh)       # add to ~/.zshrc")
    console.print("  [dim]# fish[/dim]  kq completion fish | source")


def run(argv: list[str]) -> int:
    if not argv or argv[0] in ("-h", "--help"):
        _usage()
        return 0
    shell = argv[0]
    if shell not in _GENERATORS:
        from kube_q.cli.renderer import console

        console.print(
            f"[red]Unsupported shell:[/red] {shell}. "
            f"Choose one of: {', '.join(SHELLS)}."
        )
        return 2
    # Print the raw script to stdout (must be `source`-able — no Rich styling).
    print(script_for(shell), end="")
    return 0
