{{- $ns := .Values.namespace | default .Release.Namespace }}
{{- range .Values.pvcs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $ns }}
spec:
  accessModes:
{{- range .accessModes }}
    - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .storage }}
  volumeMode: Filesystem
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end }}
  {{- if .selectorLabels }}
  selector:
    matchLabels:
{{- range $key, $value := .selectorLabels }}
      {{ $key }}: {{ $value }}
{{- end }}
  {{- end }}
{{- end }}
